name: AxisLunchDevBranch

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Lint Cloudformation template
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: "**/*.yaml"

  sam:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.DEFAULT_REGION }}

    - name: SAM build
      env:
        SAM_CLI_TELEMETRY: 0
      run: |
        sam build --use-container

    - name: SAM deploy
      env:
        SAM_CLI_TELEMETRY: 0
      run: |
        sam deploy --no-fail-on-empty-changeset

    - name: Copy HTML files
      env:
        BUCKET: ${{ secrets.BUCKET }}
      run: |
        aws s3 sync html/ s3://$BUCKET

    - name: Run stepfunction
      run: |
        ARN=$(aws cloudformation describe-stacks --query 'Stacks[?StackName==`axisLunch`].[Outputs[?OutputKey==`StatemachineArn`].OutputValue]' --output text)
        aws stepfunctions start-execution --state-machine-arn $ARN