name: PurgeDevEnv

on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  delete-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.DEFAULT_REGION }}

    - name: purge dev environment
      run: |
        STACK=$(aws cloudformation describe-stacks --query 'Stacks[?StackName==`'${{ secrets.STACK_NAME_DEV }}'`].[StackId]' --output text)
        RESULT=$(if [ -z "$STACK" ]; then echo "No DEV stack present"; else echo $STACK && aws cloudformation delete-stack --stack-name $STACK; fi)